version: "3.8"

services:
  qcm_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qcm_app
    ports:
      - "8501:8501"
    # Volume pour les le√ßons SEULEMENT
    volumes:
      - ./data/lessons:/app/lessons
    environment:
      - PYTHONUNBUFFERED=1
